// "use client";

import AuthProvider from "@/components/AuthProvider";
import Navbar from "@/components/Navbar";
// import { Header } from "@/stories/Header";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <Toaster />
          <main className="h-screen flex flex-col justify-center items-center">
            <Navbar />
            {/* <Header /> */}
            {children}
          </main>
        </body>
      </AuthProvider>
    </html>
  );
}
